### ISSUE TITLE
closing automatically after 40 users only

### ISSUE THREAD

**Issue by rahulmasal** [Cryptonian007/Genisys#2]
peer flood error

**Comment by Cryptonian007** [comment]
If you are adding by username, all users may not get added as all users don't have usernames
If you are adding by ID, all users may not get added due to privacy restrictions or early API restriction from Tg
On an avg, this tool adds about 50-60 accounts. Try with another account
Hope it helps 😃 
PS: sorry for late reply, I was damn busy preparing for 10th boards
